version: 2
updates:
  - package-ecosystem: "docker"
    directory: "."
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pip"
      directory: "/backend"
      open-pull-requests-limit: 1
      schedule:
        interval: "weekly"
