services:
  db:
    image: postgres:latest
    container_name: face-analyze-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: super-user
      POSTGRES_PASSWORD: super-password
      POSTGRES_DB: face-analyze
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
