# Error msg
ENTITY_ALREADY_EXISTS = "Entity already exists"
INCORRECT_PASSWORD = "Incorrect password"
VALIDATE_CREDENTIALS_ERROR = "Could not validate credentials"
USER_NOT_FOUND = "User not found"
FAILED_SEND_SMS = "Failed to send SMS code"
CONFIRMATION_ERROR = "Verification code has expired or number is invalid"
INVALID_DATA_STORED = "Invalid data stored in database"
UNEXPECTED_TOKEN_TYPE = "Unexpected token type"
USER_NOT_ADMIN = "User is not admin"
